export const SIMPLE_REQUIREMENT_WORK_ORDERS = [
  'CLIPPING',
  'FINISHING',
  'PASSING',
  'METAL DETECTION',
];

export const RAW_MATERIAL_WORK_ORDER_OPTIONS = [
  'WEAVING',
  'TUFTING',
  'QUILTING',
  'PRINTING',
  'KNITTING',
  'EMBROIDERY',
  'DYEING',
  'BRAIDING',
  'CARPET',
  'CUTTING',
  'SEWING',
  'FRINGE/TASSELS',
  ...SIMPLE_REQUIREMENT_WORK_ORDERS,
];
